### PR TITLE
feat(PLA-286): help user joining corres game

### PR DESCRIPTION
**Pull request by vincentfrochot**

### CODE REVIEW

**Review by JamesHeppell — APPROVED** [review]
Great that fixes the issue. We could direct the user to the game they just clicked on but perhaps not that useful in correspondence and when its not their first move? Did you already consider this?

**Comment by vincentfrochot** [comment]
@JamesHeppell indeed I tried to see if I could just redirect to the game directly and I did not achieve to do that, so I proceeded in another way and thought it was OK since it's correspondence games. I thought maybe I should emit a message that lila-ws can send back to both the joiner AND the one who created the game, because actually for the one who created the game, the game just disappear from the list ?
Glad that you agree it solves the issue, but if you find some time please let me know (or give me tips) how I could have done.

**Comment by JamesHeppell** [comment]
I would look at how the lobby games (real time) are handled. It looks like the game id is stored in the data-id attribute, therefore you can redirect the user to the correct url for that new game. 
You don't want to redirect the creator as they could be off doing something else as the correspondence games stay even when in a tournament.

**Comment by vincentfrochot** [comment]
I thought about that but it seemed the data-id for correspondence games does not corresponds to the same kind of ID I could use to redirect to the new game. I'll give it another look then, thank you !

**Comment by JamesHeppell** [comment]
maybe you are right, it has 8 characters so I've just assumed it is fine.

**Pull request merged**
