### PR TITLE
Issue 47 - improve micro match display - add a tooltip and definition

### PR DESCRIPTION
**Pull request by JamesHeppell**
Not quite sure where [trans.microMatchExplanation](https://github.com/Mind-Sports-Games/lila/blob/master/app/views/setup/bits.scala) text is rendered? And therefore if we want to tweak it to match the newer definition. Thoughts?
Also it looks like you can have a micromatch via a [challenge ](https://github.com/Mind-Sports-Games/lila/blob/master/app/views/challenge/bits.scala) but I cant see where that is.....

### CODE REVIEW

**Comment by JamesHeppell** [comment]
I would like to link the relevant issue to this PR? As it's from a different repo I haven't figured it out yet....

**Comment by JamesHeppell** [comment]
github/Mind-Sports-Games/tasks/#59

**Comment by msomatt** [comment]
The 'double rounds' shouldnt be a link (as it doesnt have anywhere to link to). I'm pretty sure I found a place where there was a tooltip that wasnt a link (something like the start time of an upcoming tournament?) I'd prefer 'micro-match rounds' used as the term 'Micro-match' is used elsewhere on the site (see below) and isnt just an internal term.

>  Also it looks like you can have a micromatch via a challenge but I cant see where that is.....
If you do 'Play With Friend' and then select Draughts > From Position you'll see it. Not sure why its only there but that's how to get into it. This is where trans.microMatchExplanation is used. Im not wild on that 'explanation', I prefer yours, so could make them be the same if you think its appropriate

**Review by msomatt — CHANGES_REQUESTED** [review]
The 'double rounds' shouldnt be a link (as it doesnt have anywhere to link to). I'm pretty sure I found a place where there was a tooltip that wasnt a link (something like the start time of an upcoming tournament?) I'd prefer 'micro-match rounds' used as the term 'Micro-match' is used elsewhere on the site (see below) and isnt just an internal term.

> Also it looks like you can have a micromatch via a challenge but I cant see where that is.....

If you do 'Play With Friend' and then select Draughts > From Position you'll see it. Not sure why its only there but that's how to get into it. This is where trans.microMatchExplanation is used. Im not wild on that 'explanation', I prefer yours, so could make them be the same if you think its appropriate

**Comment by JamesHeppell** [comment]
I've made the changes you suggested. Let me know...

**Review by msomatt — APPROVED** [review]
Possibly 'Each round' doesnt make much sense when creating a 'from position' one off micro-match?
I guess the 'automatic' assurance was also useful information that has been removed.
I dont care that much though, I'll let you make a final judgement and merge :)

**Pull request merged**
